# Generated by Django 4.0.5 on 2022-07-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='EsetProduct',
        ),
    ]
