# Generated by Django 4.0.5 on 2022-07-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productextra',
            name='desc',
            field=models.TextField(default='', verbose_name='desc'),
        ),
    ]
