# Generated by Django 4.0.5 on 2022-08-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productextra_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='order id'),
        ),
    ]
