# Generated by Django 4.0.5 on 2022-07-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
        ('product', '0002_rename_product_esetproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EsetProduct',
            new_name='Product',
        ),
    ]
