# Generated by Django 4.0.5 on 2022-07-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_esetproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
