# Generated by Django 4.0.5 on 2022-08-06 11:19

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_alter_productextra_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64, verbose_name='company name')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('email', models.EmailField(max_length=120, verbose_name='email')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='phone number')),
                ('quantity', models.BooleanField(verbose_name='quantity')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('contact_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
