# Generated by Django 4.0.5 on 2022-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='quantity',
            field=models.IntegerField(blank=True, default=True, null=True, verbose_name='quantity'),
        ),
    ]
