# Generated by Django 4.0.5 on 2022-08-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_image_top'),
        ('product', '0006_product_order_id'),
        ('contact', '0004_alter_contact_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InQueryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'InQuery Type',
                'verbose_name_plural': 'InQuery Types',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
        migrations.AddField(
            model_name='contact',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='product.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='contact',
            name='inquery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.inquerytype', verbose_name='inquery type'),
        ),
    ]
