# Generated by Django 4.0.5 on 2023-03-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_contact_first_name_remove_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
