# Generated by Django 4.0.5 on 2022-07-27 14:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='image')),
                ('body', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('theme', models.CharField(blank=True, max_length=64, null=True, verbose_name='Theme')),
            ],
        ),
    ]
