# Generated by Django 4.0.5 on 2022-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_config_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='description',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='description'),
        ),
    ]
