# Generated by Django 4.0.5 on 2022-08-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_config_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='config_img/', verbose_name='image'),
        ),
    ]
