# Generated by Django 4.0.5 on 2022-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('discount', models.IntegerField(verbose_name='discount')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'PERCENT'), ('AMOUNT', 'AMOUNT')], max_length=50, verbose_name='discount type')),
                ('start_at', models.DateTimeField(verbose_name='starts at')),
                ('end_at', models.DateTimeField(verbose_name='ends at')),
                ('promotion_type', models.CharField(choices=[('ON_COLLECTION', 'ON_COLLECTION'), ('ON_PRODUCT', 'ON_PRODUCT'), ('WITH_CODE', 'WITH_CODE')], max_length=50, verbose_name='promotion type')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='code')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('collections', models.ManyToManyField(blank=True, related_name='promotions', to='product.collection', verbose_name='collections')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='product.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
    ]
