# Generated by Django 4.0.5 on 2022-07-25 14:20

from django.db import migrations, models
import payment_gateway.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.CharField(default=payment_gateway.models.gen_id, max_length=64, primary_key=True, serialize=False, verbose_name='id')),
                ('amount', models.BigIntegerField(verbose_name='amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ref id')),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='tracking code')),
                ('card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='card number')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='ip')),
                ('gateway_port', models.CharField(default='GARDESHPAY', max_length=50, verbose_name='gateway port')),
                ('status', models.CharField(choices=[['INIT', 'INIT'], ['FAILED', 'FAILED'], ['SUCCEED', 'SUCCEED']], default='INIT', max_length=50, verbose_name='status')),
                ('callback', models.CharField(max_length=64, verbose_name='callback')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='payment date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
            },
        ),
    ]
