# Generated by Django 4.0.5 on 2022-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
